# docker build -t comicgator/maestro:dev -f Dockerfile.dev .
# docker run -it --name maestro-dev -v $PWD:/home/c11z/maestro comicgator/maestro:dev
FROM debian:jessie

MAINTAINER Cory Dominguez <mr@comicgator.com>

ARG project_name=maestro
ARG user=c11z

# Development application ENV
# Application
ENV APPLICATION_SECRET 8Vz>klF16_mNUwYN1Mr@e^=vL37Ydj/kRT^808y18TCNm5DoY<wdz_hb9C[SKV<B
ENV COMIC_GATOR_HOSTNAME http://localhost:9000

# Database
ENV DATABASE_URL jdbc:postgresql://0.0.0.0:5432/cdb
ENV DATABASE_USER mrcg
ENV DATABASE_PASSWORD mrcg

# Install dependencies
RUN apt-get update && \
apt-get install -y git build-essential curl wget zip unzip software-properties-common locales sudo

# make the "en_US.UTF-8" locale so system will be utf-8 enabled by default
RUN rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

# Fix sh, replace dash with bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Create editor userspace
RUN groupadd $user
RUN useradd $user -m -g $user -s /bin/bash
RUN passwd -d -u $user
RUN echo "$user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$user
RUN chmod 0440 /etc/sudoers.d/$user
RUN mkdir -p /home/$user/$project_name
RUN chown $user:$user /home/$user/$project_name

# Install sbt
RUN echo "deb http://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list && \
apt-get update && \
apt-get install -y --force-yes sbt

# Install Java and dependencies
RUN \
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections && \
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list && \
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list && \
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 && \
apt-get update && \
apt-get install -y oracle-java8-installer oracle-java8-set-default
# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
# Based on https://github.com/cmoro-deusto/docker-play/issues/4
# Define user home. Activator will store ivy2 and sbt caches on /home/$user
RUN echo "export _JAVA_OPTIONS='-Duser.home=/home/$user'" >> /home/$user/.bashrc

# Change user, launch bash
USER $user
WORKDIR /home/$user
CMD ["/bin/bash"]

# Expose Code volume and play ports 9000 default 9999 debug 8888 activator ui
VOLUME "/home/$user/$project_name"
EXPOSE 9000
EXPOSE 5005
WORKDIR /home/$user/$project_name