version: '2'
services:
  maestro:
    container_name: maestro
    image: comicgator/maestro:dev
    ports:
      - "9000:9000"
      - "5005:5005"
    volumes:
      - ./maestro:/home/c11z/maestro
    environment:
      - APPLICATION_SECRET=8Vz>klF16_mNUwYN1Mr@e^=vL37Ydj/kRT^808y18TCNm5DoY<wdz_hb9C[SKV<B
      - COMIC_GATOR_HOSTNAME=http://localhost:9000
      - DATABASE_URL=jdbc:postgresql://cdb:5432/cdb
      - DATABASE_USER=mrcg
      - DATABASE_PASSWORD=mrcg
      - MAILGUN_DOMAIN=sandboxf3add8e069384dc5853ed751ba714836.mailgun.org
      - MAILGUN_API_KEY=key-902d3c26c20740199daea1819693a071
    tty: true
    links:
      - cdb
  cdb:
    container_name: cdb
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mrcg
      - POSTGRES_PASSWORD=mrcg
      - POSTGRES_DB=cdb
      - PGDATA=/var/lib/postgresql/data
  lunchtime:
    container_name: lunchtime
    image: comicgator/lunchtime:dev
    ports:
      - "3000:3000"
    volumes:
      - ./lunchtime:/home/c11z/lunchtime
    tty: true
    environment:
      - REACT_APP_MAILGUN_PUBLIC_API_KEY=pubkey-c7126e4cab251d643298f658eae14a84
      - REACT_APP_MAESTRO_HOST=http://localhost:9000