package models

import org.bson.types.ObjectId

/**
  * Object describing Comic Strip
  * @param id Object id uniquely identifying a Strip
  * @param comicId Comic Associated with the Strip
  * @param thumbnailUrl String image url for a thumbnail to be eventually generated by Lurker.
  * @param scrap Scrap class of values reaped from the html.
  */
case class Strip(id: ObjectId, comicId: ObjectId, thumbnailUrl: String, scrap: Scrap)


/**
  * Object representing the outcome of the scraped comic strip webpage.
  * @param number Counter for tracking order of comics by release.
  * @param checksum String MD5 hash of the image url used for uniquely identifying the comic.
  * @param imageUrls Vector of image url strings. (Required)
  * @param title String the text of the title.
  * @param bonusImageUrl String the url of the bonus image.
  * @param imageTitle String the text of the title text of the comic image.
  * @param imageAlt String the text of the alt text of the comic image.
  */
case class Scrap(number: Int, checksum: String, url: String, imageUrls: Vector[String], title: Option[String],
                 imageTitle: Option[String], imageAlt: Option[String], bonusImageUrl: Option[String], isSpecial: Boolean)

